tscenping/BE

src/channels/channels.repository.ts, src/channels/channels.service.ts
주요 변경점
< totalDataSize >
before: 프론트에서 totalDataSize를 통해 전체값을 리턴해주어야 하는데, 페이지네이션 된 카운트만 리턴해주었음
after: totalDataSize에서 전체값을 리턴해주도록 변경
< userCount >
쿼리문에 유저 카운트를 가지고 오지 못하는 문제점이 있어서 groupby를 통해 집계함수를 사용함
< DMCount >
User 테이블과 Channel user 테이블 그리고 channel 테이블의 조인
cu."channelId", cu."userId" as "PartnerName", u."status" 로 가지고 오도록 변경
=> DTO 타입에 따른 Query재 작성

src/channels/channels.controller.ts, src/channels/channels.repository.ts, src/channels/channels.service.ts
query minor changes:
서브쿼리를 통해 유저가 참여하고 있는 방의 전체 인원수를 반환하도록 변경
channel repository의 'countInvolved' 함수를 추가하여 userID 를 가지고 있는 채널의 갯수만 리턴할 수 있도록 변경함
=> few query changes

src/channels/channels.controller.ts, src/channels/channels.repository.ts, src/channels/dto/update-channel-user-request.dto.ts
- PATCH /channels/exit  
- api call 시 request body의 channelId 유효성 검사를 하고있지 않아 추가했습니다.
- GET /channels/all
- api call 시 response data인 userCount 값을 구할 때 채널을 나간 유저까지 합계하는 것을 수정했습니다.
=> fix: add channelId validation and modify findAllChannel query

src/channels/channels.controller.ts, src/channels/channels.repository.ts, src/channels/channels.service.ts, src/channels/dto/creat-channel-request.dto.ts, src/channels/dto/dmchannel-list-return.dto.ts
< 주요 변경점 >
findAllChannels:
**service, controller**
- 쿼리정보를 가지고 오지 못하게 된다면, 500 서버에러에서 400에러가 되도록 변경했습니다.
**Repository**
-채널을 가져올 때, isJoined 컬럼을 통해 요청을 보내는 유저가 존재하는 채널을 확인하는 컬럼을 추가했습니다.
- 채널에 존재하면 1, 존재하지 않으면 0을 반환하도록 했습니다.
- 모든 채널을 가져올 때 userID가 필요해서 service, controller 에 userID의 파라미터를 가지도록 추가해주었습니다.
findMyChannels: 
- DM 목록은 조회하지 않도록 했습니다.
- 배치를 최신순으로 배치하도록 했습니다.
findDmChannels:
- partnerName을 유저 id로 가지고 있지 않고 nickname을 가질 수 있도록 변경해주었습니다.
- 배치를 최신순으로 배치하도록 했습니다.
src/channels/dto/dmchannel-list-return.dto.ts  멤버추가
src/channels/dto/creat-channel-request.dto.ts 순서변경
=> feat: added new queries(isJoined, avatar, ... ) and change Error messages

package-lock.json, package.json, src/app.module.ts, src/app.service.ts, src/auth/auth.controller.ts, src/users/ranks.service.ts, src/users/users.controller.ts, src/users/users.module.ts, src/users/users.repository.ts
유저가 생성됨과 동시에 레디스에 initializing 헤줍니다.
- 'zadd' 사용시 score으로 정렬이 되도록 변경해주었습니다.
주기적으로(10분) 메인DB postgreSQL에서 유저를 가지고 와서 레디스에 업데이트 하는 작업을 합니다.
- NestJS에서 지원하는 크론잡으로 redis가 올라가있을때에는 업데이트가 가능하도록 수정해주었습니다.
ref : [https://docs.nestjs.com/techniques/task-scheduling](url)
=> feat: update user ranking data for every 10minute  #56

src/users/ranks.service.ts, src/users/users.controller.ts
- 기존의 랭크 pagination 에서 랭킹API 가 너무많이 호출되는 우려되는 상황으로 인해, 전체의 랭크데이터를 불러오는 것으로 변경했습니다.
- 또한, ranking 데이터를 외부에서 확인할 수 있도록 수정해주었습니다.
- user.controller의 '/ranks'를  userGuards를 제외하여 토큰인증없이도 랭킹데이터를 조회 가능하도록 변경했습니다.
=> feat(users): change '/ranks' without guards, pagination to chunked data

src/socket-adapter/socket-io.adapter.ts
- 클라이언트가 websocket 연결 요청시 cors error 나는 문제
- 첫 http handshake시에 문제가 생기는 것 같은데, .enableCors로 해결이 안됩니다.
- 저번에 만들었던 SocketIoAdapter에서 서버를 만들 때, cors 옵션을 줘봤습니다.
- 일단 되는지 확인 예정!
=> feat: socket.io cors errror solving

src/auth/auth.controller.ts, src/auth/auth.module.ts, src/channels/channels.gateway.ts, src/channels/channels.module.ts, src/game/dto/create-game-param.dto.ts, src/game/dto/gateway-join-room-param.dto.ts, src/game/game-invitation.repository.ts, src/game/game.controller.ts, src/game/game.gateway.ts, src/game/game.module.ts, src/game/game.repository.ts, src/game/game.service.ts
- 현재 코드 상에서는 game invite를 받기 위해 game socket을 연결시켜야합니다. 
하지만 invitation은 ONLINE이기만 해도 받을 수 있어야한다고 생각하며, game socket의 연결 시점은 game이 확정된 이후여야 한다고 생각합니다 !
**그래서 GameGateway의 inviteGame을 ChannelsGateway로 옮겼습니다. .** 
- ChannelsGateway가 싱글톤 패턴으로 생성되지 않는 문제가 있었습니다! AuthModule과 ChannelsModule 두곳의 providers 배열에 포함되어 있던 ChannelsGateway가(AuthModule에서는 gateway를 갖다쓰려다가 만 것 같습니다) 두개의 인스턴스가 되어 연결 요청과 메세지 수신을 동시에 받고있었던 것입니다.
우리는 @Injectable @Module (+ @WebSocketGateway) 데코레이터가 싱글톤 패턴을 무조건 보장한다고 알고있었습니다. 하지만 ! 각기 다른 모듈의 providers에 중복되어 포함되는 클래스들은 싱글톤이 보장되지 않더군요 !  !
**그래서 ChannelsGateway를 export하고, ChannelsGateway를 쓰는 다른 모듈에서는 ChannelsModule을 import 해주었습니다.**
추후 모듈 정리도 하고싶군요.
- GameGateway disconnect 예외처리시 잘못된 조건문때문에 user의 gameSocketId가 지워지지 않고 있었습니다. 조건문을 수정해주었습니다.
- 게임 초대 수락 로직 진행중
=> fix: channel gateway, game gateway 수정

src/channels/channel-invitation.repository.ts, src/channels/channels.controller.ts, src/channels/channels.gateway.ts, src/channels/channels.service.ts, src/game/dto/gateway-create-channelInvitation-param-dto.ts
채널 join이 안되는 이슈가 있어서 messageDTO에 channelId 추가했읍니다.
PrivateAlert구현 진행중에 있습니다
=> WIP: add some channel socket logics

package-lock.json, package.json, src/channels/channels.gateway.ts, src/common/events.ts, src/game/dto/create-game-param.dto.ts, src/game/dto/create-invitation-request.dto.ts, src/game/dto/delete-invitation-param.dto.ts, src/game/dto/delete-invitations-param.dto.ts, src/game/dto/game-param.dto.ts, src/game/dto/gateway-create-invitation-param.dto.ts, src/game/dto/gateway-join-game-room-param.dto.ts, src/game/dto/gateway-send-invitation-reaponse.dto.ts, src/game/game-invitation.repository.ts, src/game/game.controller.ts, src/game/game.gateway.ts, src/game/game.module.ts, src/game/game.repository.ts, src/game/game.service.ts
- 게임 초대를 취소하는 api 
- 게임 초대를 수락하는 api
- 게임을 생성하고 초대 보낸 사람과 받은 사람 모두에게 gameInvitationReply 이벤트를 보냅니다
- 게임 초대를 거절하는 api
- 초대 보낸 사람에게 gameInvitationReply 이벤트를 보냅니다
- inviteGame 등 ChannelsGateway의 서버 소켓이 필요한 메서드들의 경우,
GameGateway에서 ChannelsGateway를 주입 받아 ChannelsGateway의 server에 접근합니다.
(+)
- 게임 초대시 받는 사람이 보낸 사람을 block한 상태라면, 
보낸 사람은 보내진 것으로 처리되고(201 created response) 받는 사람은 'gameInvitation' 이벤트를 받지 않습니다.
=> fix: 게임 초대하기 취소, 수락 및 거절 로직

src/channels/channels.controller.ts, src/channels/channels.gateway.ts, src/channels/dto/channel-notice.response.dto.ts, src/channels/dto/event-message-on.dto.ts, src/common/enum.ts
- /channels/accept에 response 가 제대로 가지 않는 문제가 있었습니다. return을 추가했습니다.
- /channels/notice 소켓 이벤트를 구현중입니다.
=> WIP: /channels/accept 리턴 타입 수정 및 /channels/notice 구현 진행 중 #52

src/channels/channels.controller.ts, src/channels/channels.service.ts
- kick, ban에서 channelId를 찾지 못하는 오류 수정
이미 삭제된 receiverChannelUser의 channelUserId 값을 이용해 channelId를 찾으려고 해서 발생하는 문제였습니다. giverUser의 userId 값을 이용해 channelId를 찾는 것으로 수정했습니다.
- kick, ban, mute, admin 시 소켓의 nickname을 receiver의 nickname으로 수정 #52
프론트의 요청으로 수정했습니다.
- 머지하고 sangyeki한테 알려주시면 감사하겠습니당
=> fix: kick, ban, mute, admin 시 notice 소켓 이벤트 수정

src/channels/channels.controller.ts, src/channels/channels.service.ts
- channelId를 channelUser 엔티티에서 giverUserId로 찾으면 여러 채널에 나올 수 있습니다.
- receiverChannelUserId를 이용해 channelUserId를 찾되, 채널유저 삭제 이전에 수행하도록 순서를 변경했습니다.
=> fix: kick, ban에서 channelId를 찾지 못하는 오류 수정 #52

src/channels/channels.service.ts, src/common/events.ts, src/game/dto/create-initial-game-param.dto.ts, src/game/dto/delete-invitations-param.dto.ts, src/game/dto/emit-event-invitation-reply.dto.ts, src/game/dto/emit-event-match-score-param.dto.ts, src/game/dto/emit-event-match-status.dto.ts, src/game/dto/emit-event-server-game-ready-param.dto.ts, src/game/dto/game.dto.ts, src/game/dto/gateway-join-game-room-param.dto.ts, src/game/dto/view-map.dto.ts, src/game/game.controller.ts, src/game/game.gateway.ts, src/game/game.repository.ts, src/game/game.service.ts
=> fix: maxscore 7로 수정, server game ready 이벤트

src/common/events.ts, src/game/dto/emit-event-invitation-reaponse.dto.ts, src/game/dto/emit-event-matchmaking-param.dto.ts, src/game/dto/match-game-delete-param.dto.ts, src/game/dto/match-game-param.dto.ts, src/game/game.controller.ts, src/game/game.gateway.ts, src/game/game.service.ts
- 매치메이킹을 위한 게임 큐를 3가지 구성했습니다.
1.  래더게임 큐(LADDER)
2. 노말모드 게임 큐(NORMAL_MATCHING)
3. 스페셜모드 게임 큐(SPECIAL_MATCHING)
- 유저가 2명이상 존재하게 된다면 매치메이킹 로직을 통한 gameDB가 구성됩니다.
1. 게임 큐에서 유저가 2명 이상일때 gameQueue에서 유저를 뽑아서 할당해줍니다.(shift)
2. 뽑아온 유저중 channelSocketId가 존재하지 않는다면 gameQueue에 존재하는 다른유저를 뽑아와서 해당 player을 대체합니다.
3. 유저에게 gameId를 emit 해줍니다.
- 매치메이킹 취소로직을 구성했습니다.
1. gameType을 받고, 큐에 유저가 있는지 검사합니다.
2. 유저가 존재한다면, 유저를 큐에서 삭제합니다. (splice)
3. 유저가 존재하지 않는다면 매칭큐에 존재하지 않는다는 에러메세지를 던집니다.
=> feat(game): add game queue matchmaking logics

src/channels/channels.gateway.ts, src/channels/channels.service.ts, src/channels/entities/channel.entity.ts, src/game/game.module.ts, src/game/game.service.ts
- client가 매칭을 돌리고 있는 상태에서 새로고침을 하게될 때 gameQueue에서 빠져나오지 않는 버그를 수정했습니다.
- 기존에는 한유저가 매칭버튼을 누르고 새로고침을 해서 매칭을 다시 돌리게 된다면 자신과의(?) 매칭이 이뤄졌습니다.
1. channelGateway에 gameQueue를 재배치시켰습니다. 이를 통해 순환 의존성을 줄이고, 채널에서 Disconnect해줄때 용이하도록 했습니다.
2. user정보를 받아서 래더, 노말매치, 스페셜매치를 모두 순회하여 유저를 배제시키는 방식으로 구성했습니다.
-'/match' Delete api 에서 유저삭제가 안되는 버그를 수정했습니다.
- 유저정보를 들고 있는 gameQueue에서 매칭 취소를 해도 gameQueue에서 빠져나오지 않았습니다. 
1. User정보의 객체를 찾기위해 user.id와 매칭해서 찾아야 하는방식으로 찾도록 구성했습니다.
2. gameQueue에 아무도 없다면 return 해서 매칭을 나올 수 있도록 구성했습니다.
=> feat(game): clear gameQueue when client disconnected

src/auth/auth.controller.ts, src/users/ranks.service.ts
- 유저랭킹을 업데이트 하는 방식을 한가지로 통일했습니다. 기존에는 두가지 방법으로 redis에 유저랭킹을 업데이트를 했습니다.
1. 최초로 유저 생성을 해주었을 때 바로 업데이트
2. 10분마다 크론잡 업데이트
닉네임이 업데이트 되지 않은 상황인데, DB에는 먼저 initializing 되는 경우가 생겼음
- 처음에 1번을 고려한 이유는 캐시와 DB의 데이터 일관성이 더 중요하다고 생각했었음
- 그러나 위 문제가 생기고 생각한건 정합성을 위반하지 않기위해 주기적으로만 잘 업데이트만 시켜주기만 하면 될 것 같다고 생각함
- 결론적으로, 닉네임이 초기화 되지 않은 유저는 크론에서 한번 걸러주고 랭킹에 업데이트 해주는 방식으로 통일하는 방식으로 구현함
=> fix(ranking): update ranking user only by cronjob

src/channels/channels.controller.ts, src/channels/channels.gateway.ts, src/channels/channels.service.ts, src/channels/dto/channel-name-change-response.dto.ts, src/channels/dto/create-channel-request.dto.ts, src/channels/dto/update-channel-name-param.dto.ts, src/channels/dto/update-channel-name-request.dto.ts, src/common/enum.ts
* 채널 이름을 수정하는 api를 만들었습니다.
* 이름 유효성 기준은 채널 생성할 때와 같습니다.
* 채널 이름을 채널 유저들에게 알리는 nameChange 이벤트도 생겼습니다.
=> feat: 채널 이름 수정 api 구현

package-lock.json, package.json, src/app.module.ts, src/auth/auth.controller.ts, src/auth/dto/user-signin-response.dto.ts, src/channels/channel-invitation.repository.ts, src/channels/channels.controller.ts, src/channels/channels.gateway.ts, src/channels/channels.module.ts, src/channels/channels.service.ts, src/channels/dto/create-invitation-param.dto.ts, src/common/guards/ws-auth.guard.ts, src/config/redis.config.ts, src/config/s3.config.ts, src/config/swagger.config.ts, src/game/game.gateway.ts, src/users/users.controller.ts, src/users/users.service.ts
1. privateAlert에서 던져지는 에러가 문제를 일으켰습니다
- 그래서 ChannelGateway에서 초대한 유저와 받은 유저가 유효한지를 검사하는게 맞나? 의문이 들어서 privateAlert 함수의 로직을 ChannelService로 옮겼읍니다.
2. 채널 소켓이 disconnect될 때 db를 업데이트하지 못하는 문제가 있었습니다.
- 예전에 발견했던 문제입니다 handleDisconnect에 WsAuthGuard가 적용되지 않습니다 그래서 연결시 socketIoAdapter에서 넣어줬던 user 객체를 그대로 씁니다. user의 channelSocketId가 null이어서 if (!user || client.id !== user.channelSocketId) 조건문에 걸리는 것이었습니다.  진짜 의도는 이게 이미 끊긴 client인지 거르는 것이라 생각해서 단순하게 if (!user || !client.id)로 바꿨습니다. 
3. 외부의 s3 버킷 접근을 위한 preSignedUrl 을 발급해주는 api들을 추가했습니다.
=> fix: privateAlert channelService에서 하기, 소켓 끊길 때 db 업데이트 잘하기, s3 이미지 api 추가

src/auth/auth.controller.ts, src/auth/auth.service.ts, src/auth/dto/signup-request.dto.ts, src/channels/dto/channel-Invitation-list-return.dto.ts, src/channels/dto/channel-user-info-return.dto.ts, src/channels/dto/dmchannel-list-return.dto.ts, src/common/constants.ts, src/friends/dto/block-user-return.dto.ts, src/friends/dto/friend-user-return.dto.ts, src/game/dto/emit-event-match-end-param.dto.ts, src/game/dto/emit-event-server-game-ready-param.dto.ts, src/user-repository/dto/my-profile-response.dto.ts, src/user-repository/dto/user-profile-return.dto.ts, src/user-repository/entities/user.entity.ts, src/user-repository/users.repository.ts, src/users/dto/rank-user-return.dto.ts, src/users/dto/user-profile-response.dto.ts, src/users/ranks.service.ts, src/users/users.controller.ts, src/users/users.service.ts
*노션 api 페이지 참고*
s3 이미지 업로드는 preSignedUrl을 기반으로 진행됩니다.
업로드 주체는 클라이언트이고, s3 버킷에 접근 권한을 가진 서버에서 클라이언트에게 접근 url을 발급해줍니다.
기존과 달라진 점은 **회원가입과 아바타 수정 api 에서 avatar 데이터를 boolean 값으로 받습니다**. 
true일때
* User 데이터베이스의 avatar 값을 '고정 url + 유저 닉네임 + 날짜' string 값으로 업데이트 합니다.
* preSignedUrl을 발급받아 string값을 응답 데이터로 줍니다.
false라면 
* 회원가입시에는 nickname만 업데이트하고, 수정시에는 avatar 값을 null로 업데이트합니다.
* preSignedUrl이 null인 응답 데이터를 줍니다.
=> fix: s3 image 업로드 로직 수정
