tscenping/BE

- src/auth/auth.controller.ts
- src/auth/auth.module.ts
- src/auth/auth.service.ts
- src/auth/dto/create-auth.dto.ts
- src/auth/dto/ft-oauth-response.dto.ts
- src/auth/dto/ft-user.dto.ts
- src/auth/dto/update-auth.dto.ts
- src/auth/dto/user-42.dto.ts
- src/auth/ft-auth.service.ts
- src/users/dto/create-user.dto.ts
- src/users/dto/update-user.dto.ts
- src/users/users.service.ts
> feat: 개발용 유저 생성 API #6

- src/channels/channel-users.repository.ts
- src/channels/dto/channel-user-info-return.dto.ts
- GET `/channels/enter/:channelId` 구현 완
> feat: 참여 채널에 대한 채널 유저 정보 조회 #16

- src/channels/channels.controller.ts
- src/channels/dto/create-channel-request.dto.ts
- src/channels/entities/channel.entity.ts
- DM 채널의 경우 채널 이름을 null로 설정
- 나머지 채널의 경우 null 불가!
> fix: DM 채널의 경우 name을 null로 설정 #16

- package-lock.json
- package.json
- src/channels/dto/create-channel-request.dto.ts
- requestDTO에서 1,10자 제한 -> 8,16자 제한으로 변경
> fix: channel password 글자수 제한 변경 #16

- src/channels/channels.controller.ts
- src/channels/channels.repository.ts
<간이 이슈 2개>
1. swagger 이슈: 문서화 작업때문에 @Apitags 등 주석처리로 빌드 안되는 문제 해결
2. 쿼리변경 : 프론트에 응답 잘 가는것 확인하고 수정함
> fix: fixed userCount issues

- src/channels/channels.repository.ts
- 조인된 테이블.deleteAt IS NULL 구문 추가
> fix: 모든 channel의 find 쿼리문에 delete된 데이터를 제외하는 쿼리 구문 추가

- src/channels/channels.service.ts
- src/channels/dto/create-channel-response.dto.ts
> feat: createChannel response에 channelId 추가 #16

- .dockerignore
- src/channels/channels.gateway.ts
- src/channels/channels.service.ts
- src/common/exception/custom-exception.ts
- src/common/exception/error-code.ts
- src/main.ts
- src/socket-adapter/socket-io.adapter.ts
- SocketIoAdapter를 구현 및 적용하였습니다. 
- closed #53 
- [노션 참고](https://www.notion.so/SocketIoAdapter-68b5a10453084733a78a83b23c9db504?pvs=4)
> feat: SocketIoAdapter 구현 및 적용

- src/socket-adapter/socket-io.adapter.ts
> fix: cors origin: http->https

- src/auth/auth.controller.ts
- src/auth/auth.module.ts
- src/channels/channels.module.ts
- src/channels/channels.service.ts
- src/common/events.ts
- src/game/dto/create-invitation-param.dto.ts
- src/game/dto/create-invitation-request.dto.ts
- src/game/dto/gateway-create-invitation-param.dto.ts
- src/game/game.controller.ts
- src/game/game.gateway.ts
- src/game/game.module.ts
- src/game/game.repository.ts
- src/game/game.service.ts
- src/main.ts
- src/socket-adapter/socket-io.adapter.ts
- src/users/users.module.ts
- POST /game/invite
- 해당 api call시 GameGateway inviteGame()를 호출합니다.
- 논의했던대로 SocketIoAdapter는 cors를 위해 존재합니다. middleware는 없어집니다!
- [노션 TIL SocketIoAdapter 를 만들어보자 (+ Guard ✨) 참고](https://www.notion.so/SocketIoAdapter-Guard-68b5a10453084733a78a83b23c9db504?pvs=4)
- game 외 디렉토리는 game 프로바이더들 주입 이슈 등으로 자잘하게 수정되었습니다. 큰 로직은 없습니다
>  게임 초대 api와 'gameInvitation' event emit을 구현했습니다.

- src/channels/channels.controller.ts
- src/channels/channels.gateway.ts
- src/channels/dto/event-message-on.dto.ts
- joinChannelRoom을 Controller에서 생략해서 메세지가 잘 안가는 문제가 있었습니다. 이전의 코드로 변경해서 다시 올렸습니다.
- 또한, 메세지 로직에 notice DTO를 추가했는데 Controller에만 반영하고 DTO를 추가못해서 빌드가 안되는 버그가 있었습니다.
- 마지막으로, 'PrivateAlert' 에서 InvitationId를 객체로 던져주었어야 하는데 값만 던져주고 있는 버그를 수정했습니다.
> fix(channel): recover joinChannelRoom logic also add notice dto

- src/channels/channels.controller.ts
모르고 enterlogic에 joinRoom한다는걸 빼먹었읍니다.. 셀프로 머리한대 쥐어박았습니다.
> fix(channels): omit enterchannelId logic

- src/channels/channel-invitation.repository.ts
- src/channels/channels.controller.ts
- src/channels/channels.gateway.ts
- src/channels/channels.service.ts
- src/channels/dto/channel-Invitation-list-response.dto.ts
- src/channels/dto/channel-Invitation-list-return.dto.ts
- src/channels/dto/channel-Invitation.dto.ts
- src/channels/dto/delete-invitation-param.dto.ts
- src/channels/dto/delete-invitations-param.dto.ts
- src/game/dto/gateway-create-channelInvitation-param-dto.ts
- 채널에서의 요청 수락과 거절 Post, Delete 구현 작업입니다
- 중간머지 필요할거같아서 PR 올립니다
> WIP: add channels accept, refuse logic

- src/channels/channels.controller.ts
- src/channels/channels.service.ts
- src/channels/entities/channel.entity.ts
- fix: PROTECTED 채널에서 비밀번호 검증 함수에 await 추가 #16
> fix: PROTECTED 채널에서 비밀번호 검증 함수에 await 추가 #16

- src/channels/channels.controller.ts
- src/channels/channels.service.ts
- src/channels/dto/channel-Invitation-list-response.dto.ts
[https://github.com/tscenping/BE/pull/76](url) <- 여기에 이어서 구현된 내용
- 채널에서의 'accept', 'refuse:invitationId' 로직을 추가했습니다.
- 채널 내부에서 초대 수락과 거절을 구현했습니다.
1. 수락에서는 invitationid 를 통해 channelId, chennelName, channelIUserType 을 반환해줍니다.
2. 거절에서는 invitationid 를 통해 요청을 보내준 사람의 invitationid를 softdelete 시켜줍니다.
> inivite 요청에 대해 accept, refuse로직을 구현했습니다.

- src/channels/channels.controller.ts
- src/channels/channels.gateway.ts
- src/channels/channels.service.ts
- src/channels/dto/channel-notice.response.dto.ts
- src/common/enum.ts
- feat: /channels/notice 구현 #52
> - feat: /channels/notice 구현 #52 

- src/channels/channels.service.ts
minor changes -> invite할 때 DB에 업데이트 되지 않는 문제를 해결했습니다.
> fix(channels): fix 'invite' don't update in db

- src/channels/channels.service.ts
-inviting logic에서 매칭큐를 돌리고 있는 사람에게 초대를 했을 때 exception을 던지지않아서 해당 로직을 추가했습니다.
> feat(invite): throw exception when invited user in queue

- src/channels/channels.service.ts
- src/game/game.service.ts
-  아까 [머지했었던](https://github.com/tscenping/BE/pull/96), 게임큐에 존재하는 유저를 체크하는 로직을 game.service로 옮겼습니다.
> fix(game): replaced invitation matched logic

- src/channels/channels.service.ts
- src/users/dto/user-profile.dto.ts
- src/users/users.repository.ts
- fix: rank가 0부터 시작하므로 1을 추가하여 프론트로 반환합니다.
> fix: 프로필 조회 시 rank value 수정

- src/channels/channels.gateway.ts
- src/common/constants.ts
- src/common/enum.ts
- src/common/events.ts
- src/common/exception/custom-exception.ts
- src/common/exception/custom-ws-exception.filter.ts
- src/common/exception/error-code.ts
- src/config/typeorm.config.ts
- src/game/dto/emit-event-match-end-param.dto.ts
- src/game/dto/emit-event-server-game-ready-param.dto.ts
- src/game/dto/game.dto.ts
- src/game/dto/update-game-result-param.dto.ts
- src/game/dto/view-map.dto.ts
- src/game/game.gateway.ts
- src/game/game.module.ts
- src/game/game.service.ts
- src/users/friends.service.ts
> feat: game 브랜치 머지 합니다

- src/app.service.ts
- src/game/dto/emit-event-match-end-param.dto.ts
- src/game/dto/game.dto.ts
- src/game/dto/view-map.dto.ts
- src/game/game.gateway.ts
- src/users/ranks.service.ts
게임 뷰
- 공이 라켓이랑 천장, 바닥 뚫지 않도록 계산 코드를 바꿨는데 (thanks to hakim & him) 
- 대신 입력 받아서 움직이는 라켓이 전보다 버벅인다 . .? 인터벌 한번(per 1/60) 에 수행하는 연산이 좀 더 많아져서 그런가 이유는 잘 모르겠군요
게임 소켓
- 게임 소켓 disconnect가 잘 안될시 유저가 게임소켓과 채널소켓을 둘다 가지는 상태가 되는데 그러면 더이상 게임을 못하는 금쪽이 유저가 되어버립니다 (문제 발생)
- 게임 소켓은 connect와 disconnect가 제한적인 상황에만 발생해서(프론트에서 게임 페이지에 보낼 때, 유저가 나갈 때 혹은 서버가 게임 페이지에서 나가게 할 때) 연결 시도가 빈번하지 않으므로 기존 연결을 끊고 새로운 연결을 받아들이는 로직으로 갑니다 (해결 방법)
- 게임을 끝내는 로직이 수정되었습니다 
- 원래는 정상 종료 아니면 모두 게임 무효화였는데 -> 몰수패가 생겼으며, 게임 시작 전 WAITING 상태에서 한쪽 유저가 disconnect 될 때만 게임이 무효화됩니다
> fix: Game 찐 최종

- src/app.module.ts
- src/auth/auth.controller.ts
- src/auth/auth.module.ts
- src/auth/auth.service.ts
- src/auth/dto/ft-user-param.dto.ts
- src/auth/dto/oauth-response.dto.ts
- src/auth/dto/oauth-userinfo-param.dto.ts
- src/auth/ft-auth.service.ts
- src/auth/google-auth.service.ts
- src/config/google.config.ts
- src/game/game.module.ts
- src/main.ts
google oauth를 추가했습니다
* ft와 로직은 비슷합니다! (client로부터 code를 받아서 처리)
* email 기준으로 user를 찾거나 생성하는 것부터 ft와 같습니다.
mfa 로직도 같은거 괜찮을까요?
ft와 중복되는 코드가 있어서.. 보기 싫네요?! 뭔가 최적화할 수 있는 방법이 있을 것 같은데(oauth 통합하기) 좀 더 찾아보겠습니다. 일단 구현부터 완!
> feat: google oauth api 구현

- src/app.module.ts
- src/auth/auth.controller.ts
- src/auth/auth.module.ts
- src/auth/auth.service.ts
- src/auth/dto/ft-user-param.dto.ts
- src/auth/dto/oauth-response.dto.ts
- src/auth/dto/oauth-userinfo-param.dto.ts
- src/auth/ft-auth.service.ts
- src/auth/google-auth.service.ts
- src/config/google.config.ts
- src/game/game.module.ts
- src/main.ts
> fix: samesite, secure 주석처리

- src/auth/auth.controller.ts
- src/auth/dto/user-signin-response.dto.ts
* 구글 로그인 api 요청 메서드를 get->post로 수정
* code를 쿼리로 받지 않고 바디로 받도록 수정
* 모든 signin 응답 데이터에 nickname 추가
> fix: 구글 로그인 요청 매핑 post로 등

- src/channels/channels.gateway.ts
- src/friends/blocks.repository.ts
- src/friends/blocks.service.ts
- src/friends/friends.controller.ts
프론트에서 요청한 페이징 없는 차단 유저 리스트 외 1개 입니다.
제목과 같습니다!
> feat: 페이징 없는 차단 유저 리스트, 채널 메세지 emit 이벤트에 아바타 추가
